networks:
  cloud1:
    driver: bridge
    name: cloud1

services:
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                    MARIADB                          #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  database:
    networks:
      - cloud1
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    expose:
      - 3306
    volumes:
      - "./srcs/db/mariadb/:/var/lib/mysql"

  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                   WORDPRESS                         #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  wordpress:
    depends_on:
      - database
    networks:
      - cloud1
    container_name: wordpress
    build: srcs/sites/wp/
    image: wordpress
    volumes:
      - "./srcs/site/wp/:/wp/"
    restart: always

  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                     NGINX                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - ./.nginxEnv
    volumes:
      - ./src/proxy/nginx/conf:/etc/nginx/templates
      - ./src/proxy/nginx/ssl:/etc/nginx/ssl
    networks:
      - cloud1