networks:
  cloud1:
    driver: bridge
    name: cloud1

services:
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                    MARIADB                          #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  database:
    networks:
      - cloud1
    container_name: mariadb
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - "./srcs/db/mariadb/:/var/lib/mysql"
    restart: always

  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                   WORDPRESS                         #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  wordpress:
    depends_on:
      - database
    networks:
      - cloud1
    container_name: wordpress
    image: wordpress
    volumes:
      - "./srcs/sites/wp/:/wp/"
    restart: always

  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                     NGINX                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  nginx:
    depends_on:
      - wordpress
    networks:
      - cloud1
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./srcs/sites/wp:/var/www/html
    restart: always
