networks:
  cloud1:
    driver: bridge
    name: cloud1

services:
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                    MARIADB                          #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  database:
    networks:
      - cloud1
    build: srcs/db/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - "./src/db/mariadb/:/var/lib/mysql"
    restart: always

  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                   WORDPRESS                         #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  wordpress:
    depends_on:
      - database
    networks:
      - cloud1
    container_name: wordpress
    build: srcs/sites/wp/
    image: wordpress
    volumes:
      - "./srcs/site/wp/:/wp/"
    restart: always

  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                     NGINX                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  nginx:
    depends_on:
      - wordpress
    networks:
      - cloud1
    container_name: nginx
    build: srcs/proxy/nginx/
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./srcs/sites/wp:/var/www/html
    restart: always
