networks:
  cloud1:
    driver: bridge
    name: cloud1
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #                    NGINX                            #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # #
services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - ./.nginxEnv
    volumes:
      - ./src/proxy/nginx/conf:/etc/nginx/templates
      - ./src/proxy/nginx/ssl:/etc/nginx/ssl
    networks:
      - cloud1

