version: '3.9'

networks:
  transcendence:
    driver: bridge
    name: cloud1

services:
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                    MARIADB                          #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
 database:
    networks:
      - cloud1
    build: srcs/db/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
    - "db/mariadb/:/var/lib/mysql"
    restart: always
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                   WORDPRESS                         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
 site:
    depends_on:
      - database
    networks:
    - cloud1
    container_name: wordpress
    build: srcs/sites/wp/
    image: wordpress
    volumes:
      - "./srcs/site/wp/:/wp/"
    restart: always

# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                     NGNINX                          #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
    nginx:
        depends_on:
          - wordpress
        networks:
          - cloud1
        container_name: nginx
        build: srcs/proxy/nginx/
        image: nginx
        ports:
          # - "80:80"
          - "443:443"
        volumes:
          - srcs/sites/wp:/var/www/html
        restart: always
